title: " Data Science Blog"
author: "Kamlesh Pandey"
description: " "


# Email and user media
emai: "kpandey@ncsu.edu"
linkedin_username: "Kamlesh Pandey"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "https://kamlespande.github.io/"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
###########################################################################################
theme: "minima"

