title: " Data Science Blog"
author: "Kamlesh Pandey"
description: " :) "


# Email and user media
emai: "kpandey@ncsu.edu"
linkedin_username: "Kamlesh Pandey"


###########################################################################################
theme: "minima"

